<!-- Footer -->
	<footer>
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-4 col-sm-12">
					<h2>Your Company</h2>
					<p>Halimun Street 25 Jakarta, Indonesia 12345</p>
					<p>www.yourdomain.com</p>
				</div>
				<div class="col-lg-6 col-md-4 col-sm-12 footer-menu">
					<div class="row">
						<div class="col-lg-4 col-md-4 col-sm-12">
							<ul>
								<li class="footer-head">Sitemap</li>
								<li>Home</li>
								<li>About</li>
								<li>Blog</li>
								<li>Menu</li>
								<li>Store</li>
								<li>Contact</li>
							</ul>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12">
							<ul>
								<li class="footer-head">Lorem Ipsum</li>
								<li>Neque</li>
								<li>Suspendisse</li>
								<li>Dictum</li>
								<li>Portitior</li>
								<li>Tincidune</li>
								<li>Enim lobartis</li>
							</ul>
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12">
							<ul>
								<li class="footer-head">Sit Amet</li>
								<li>Neque</li>
								<li>Suspendisse</li>
								<li>Dictum</li>
								<li>Portitior</li>
								<li>Tincidune</li>
								<li>Enim lobartis</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-4 col-sm-12">
					<img src="assets/img/30.png" class="img-fluid footer-logo" alt="logo">
					<h3>Copyright 2023 Karan</h3>
					<h3>Company S.L. All rights reserved.</h3>
					<ul class="footer-icon">
						<li><i class="fa-brands fa-square-facebook"></i></li>
						<li><i class="fa-brands fa-square-instagram"></i></li>
						<li><i class="fa-brands fa-square-twitter"></i></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>